package com.drinks.rules

import com.drinks.Drinks;

declare Fact
    name : String
    truthValue : Boolean
end

declare Drink
    name : String
end
 
rule "In Mexico"
    when

    then
        Fact fact = new Fact("in_mexico", false);
        boolean answer = Drinks.ask("Are you in mexico?");
        fact.setTruthValue(answer);
        insert(fact);
end

rule "PwN nOoBs"
    when
        Fact(name == "in_mexico", truthValue == false)
    then
        Fact fact = new Fact("pwn_noobs", false);
        boolean answer = Drinks.ask("Do you PwN nOoBs?");
        fact.setTruthValue(answer);
        insert(fact);
end

rule "Drink in mexico"
    when
        Fact(name == "in_mexico", truthValue == true)
    then
        System.out.println("You are in mexico");
        insert(new Drink("Jarritos"));
end

rule "Drink PwN nOoBs"
    when
        Fact(name == "pwn_noobs", truthValue == true)
    then
        System.out.println("You PwN nOoBs");
        insert(new Drink("Mountian Dew code red"));
        insert(new Drink("Jolt cola"));
        insert(new Drink("Mello yello"));
end