package com.drinks.rules

import com.drinks.Drinks;

declare Fact
    name : String
    truthValue : Boolean
end

declare Drink
    name : String
end
 
rule "In Mexico"
    when

    then
        Fact fact = new Fact("in_mexico", false);
        boolean answer = Drinks.ask("Are you in mexico?");
        fact.setTruthValue(answer);
        insert(fact);
end

rule "Drink in mexico"
    when
        Fact(name == "in_mexico", truthValue == true)
    then
        System.out.println("You are in mexico");
        insert(new Drink("jarritos"));
end

rule "Drink not in mexico"
    when
        Fact(name == "in_mexico", truthValue == false)
    then
        System.out.println("You are not in mexico");
        insert(new Drink("not_in_mexico"));
end