package com.drinks.rules

import java.util.List;
import java.util.ArrayList;
import com.drinks.Drinks;

global Drinks drinksApp;

declare enum Answer
    YES, NO;
end

declare Fact
    name : String
    answer : Answer
end

declare Drink
    name : String
end
 
rule "In Mexico"
    when
        // Empty
    then
        drinksApp.ask("Are you in mexico?", "in_mexico");
end

rule "PwN nOoBs"
    when
        Fact(name == "in_mexico", answer == Answer.NO)
    then
        drinksApp.ask("Do you PwN nOoBs?", "pwn_noobs");
end

rule "Drink in mexico"
    when
        Fact(name == "in_mexico", answer == Answer.YES)
    then
        List<Object> drinks = new ArrayList<>();
        drinks.add(new Drink("Jarritos"));
        drinksApp.presentResults(drinks);
end

rule "Drink PwN nOoBs"
    when
        Fact(name == "pwn_noobs", answer == Answer.YES)
    then
        List<Object> drinks = new ArrayList<>();
        drinks.add(new Drink("Mountian Dew code red"));
        drinks.add(new Drink("Something blue"));
        drinks.add(new Drink("Jolt cola"));
        drinks.add(new Drink("Mello yello"));
        drinksApp.presentResults(drinks);
end